# Streamlit Secrets (secrets.toml)

# 1. Jotform Credentials
JOTFORM_API_KEY = "YOUR_JOTFORM_API_KEY_HERE"
JOTFORM_FORM_ID = "201810973343553"

# 2. Gemini API Keys (add more keys separated by commas for pooling)
GEMINI_API_KEYS = "YOUR_GEMINI_API_KEY_1,YOUR_GEMINI_API_KEY_2"

# 3. Jotform Field Mapping Dictionary (Stored as a string)
JOTFORM_FIELD_MAPPING = """
{
    # Automated Fields
    "dateAnd": "dateAnd",
    "referralReceived": "referralReceived",
    "caseAssigned": "caseAssigned",
    # Referral Details
    "nameOfReferrer": "nameOf10",
    "phoneOfReferrer": "phNo12",
    "emailOfReferrer": "emailOf11",
    # Respondent's Details
    "name": "name",
    "age": "age",
    "memberOrganisation": "memberOrganisation49",
    "phoneNumber": "phoneNumber",
    "sexualOrientation": "sexualOrientation",
    "genderIdentity": "genderIdentity",
    # Consent
    "consentToStore": "doesThe56",
    "consentToUse": "doesThe",
    # Incident Details
    "dateOfIncident": "dateamp7",
    "typeOfViolation": "typeOf13",
    "charges": "ifDetainarrested",
    "perpetrators": "perpetrators",
    "caseDescription": "CaseDescription",
    # Support Needs
    "supportNeeded": "immediateReacT",
    "supportBudget": "briefDescription35"
}
"""
